version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - misspell
    - nilerr
    - unconvert
  exclusions:
    generated: strict
    presets:
      # unchecked Close, Flush, print and friends
      - std-error-handling
