// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cache_rebuilder/cache_rebuilder.proto

package cacherebpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// user_id is optional; empty string means rebuild all users.
type TriggerRebuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRebuildRequest) Reset() {
	*x = TriggerRebuildRequest{}
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRebuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRebuildRequest) ProtoMessage() {}

func (x *TriggerRebuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRebuildRequest.ProtoReflect.Descriptor instead.
func (*TriggerRebuildRequest) Descriptor() ([]byte, []int) {
	return file_cache_rebuilder_cache_rebuilder_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerRebuildRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TriggerRebuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRebuildResponse) Reset() {
	*x = TriggerRebuildResponse{}
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRebuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRebuildResponse) ProtoMessage() {}

func (x *TriggerRebuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRebuildResponse.ProtoReflect.Descriptor instead.
func (*TriggerRebuildResponse) Descriptor() ([]byte, []int) {
	return file_cache_rebuilder_cache_rebuilder_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerRebuildResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_cache_rebuilder_cache_rebuilder_proto_rawDescGZIP(), []int{2}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_rebuilder_cache_rebuilder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_cache_rebuilder_cache_rebuilder_proto_rawDescGZIP(), []int{3}
}

func (x *ResetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_cache_rebuilder_cache_rebuilder_proto protoreflect.FileDescriptor

const file_cache_rebuilder_cache_rebuilder_proto_rawDesc = "" +
	"\n" +
	"%cache_rebuilder/cache_rebuilder.proto\x12\x0fcache_rebuilder\"0\n" +
	"\x15TriggerRebuildRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"0\n" +
	"\x16TriggerRebuildResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0e\n" +
	"\fResetRequest\"'\n" +
	"\rResetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xc2\x01\n" +
	"\x15CacheRebuilderService\x12a\n" +
	"\x0eTriggerRebuild\x12&.cache_rebuilder.TriggerRebuildRequest\x1a'.cache_rebuilder.TriggerRebuildResponse\x12F\n" +
	"\x05Reset\x12\x1d.cache_rebuilder.ResetRequest\x1a\x1e.cache_rebuilder.ResetResponseBZZXgithub.com/vahan-sahakyan/distributed-social-network/pkg/grpc/cache_rebuilder;cacherebpbb\x06proto3"

var (
	file_cache_rebuilder_cache_rebuilder_proto_rawDescOnce sync.Once
	file_cache_rebuilder_cache_rebuilder_proto_rawDescData []byte
)

func file_cache_rebuilder_cache_rebuilder_proto_rawDescGZIP() []byte {
	file_cache_rebuilder_cache_rebuilder_proto_rawDescOnce.Do(func() {
		file_cache_rebuilder_cache_rebuilder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_rebuilder_cache_rebuilder_proto_rawDesc), len(file_cache_rebuilder_cache_rebuilder_proto_rawDesc)))
	})
	return file_cache_rebuilder_cache_rebuilder_proto_rawDescData
}

var file_cache_rebuilder_cache_rebuilder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cache_rebuilder_cache_rebuilder_proto_goTypes = []any{
	(*TriggerRebuildRequest)(nil),  // 0: cache_rebuilder.TriggerRebuildRequest
	(*TriggerRebuildResponse)(nil), // 1: cache_rebuilder.TriggerRebuildResponse
	(*ResetRequest)(nil),           // 2: cache_rebuilder.ResetRequest
	(*ResetResponse)(nil),          // 3: cache_rebuilder.ResetResponse
}
var file_cache_rebuilder_cache_rebuilder_proto_depIdxs = []int32{
	0, // 0: cache_rebuilder.CacheRebuilderService.TriggerRebuild:input_type -> cache_rebuilder.TriggerRebuildRequest
	2, // 1: cache_rebuilder.CacheRebuilderService.Reset:input_type -> cache_rebuilder.ResetRequest
	1, // 2: cache_rebuilder.CacheRebuilderService.TriggerRebuild:output_type -> cache_rebuilder.TriggerRebuildResponse
	3, // 3: cache_rebuilder.CacheRebuilderService.Reset:output_type -> cache_rebuilder.ResetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_rebuilder_cache_rebuilder_proto_init() }
func file_cache_rebuilder_cache_rebuilder_proto_init() {
	if File_cache_rebuilder_cache_rebuilder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_rebuilder_cache_rebuilder_proto_rawDesc), len(file_cache_rebuilder_cache_rebuilder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_rebuilder_cache_rebuilder_proto_goTypes,
		DependencyIndexes: file_cache_rebuilder_cache_rebuilder_proto_depIdxs,
		MessageInfos:      file_cache_rebuilder_cache_rebuilder_proto_msgTypes,
	}.Build()
	File_cache_rebuilder_cache_rebuilder_proto = out.File
	file_cache_rebuilder_cache_rebuilder_proto_goTypes = nil
	file_cache_rebuilder_cache_rebuilder_proto_depIdxs = nil
}
