// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: cache_rebuilder/cache_rebuilder.proto

package cacherebpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheRebuilderService_TriggerRebuild_FullMethodName = "/cache_rebuilder.CacheRebuilderService/TriggerRebuild"
	CacheRebuilderService_Reset_FullMethodName          = "/cache_rebuilder.CacheRebuilderService/Reset"
)

// CacheRebuilderServiceClient is the client API for CacheRebuilderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheRebuilderServiceClient interface {
	TriggerRebuild(ctx context.Context, in *TriggerRebuildRequest, opts ...grpc.CallOption) (*TriggerRebuildResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
}

type cacheRebuilderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheRebuilderServiceClient(cc grpc.ClientConnInterface) CacheRebuilderServiceClient {
	return &cacheRebuilderServiceClient{cc}
}

func (c *cacheRebuilderServiceClient) TriggerRebuild(ctx context.Context, in *TriggerRebuildRequest, opts ...grpc.CallOption) (*TriggerRebuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerRebuildResponse)
	err := c.cc.Invoke(ctx, CacheRebuilderService_TriggerRebuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheRebuilderServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, CacheRebuilderService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheRebuilderServiceServer is the server API for CacheRebuilderService service.
// All implementations must embed UnimplementedCacheRebuilderServiceServer
// for forward compatibility.
type CacheRebuilderServiceServer interface {
	TriggerRebuild(context.Context, *TriggerRebuildRequest) (*TriggerRebuildResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	mustEmbedUnimplementedCacheRebuilderServiceServer()
}

// UnimplementedCacheRebuilderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheRebuilderServiceServer struct{}

func (UnimplementedCacheRebuilderServiceServer) TriggerRebuild(context.Context, *TriggerRebuildRequest) (*TriggerRebuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerRebuild not implemented")
}
func (UnimplementedCacheRebuilderServiceServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedCacheRebuilderServiceServer) mustEmbedUnimplementedCacheRebuilderServiceServer() {}
func (UnimplementedCacheRebuilderServiceServer) testEmbeddedByValue()                               {}

// UnsafeCacheRebuilderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheRebuilderServiceServer will
// result in compilation errors.
type UnsafeCacheRebuilderServiceServer interface {
	mustEmbedUnimplementedCacheRebuilderServiceServer()
}

func RegisterCacheRebuilderServiceServer(s grpc.ServiceRegistrar, srv CacheRebuilderServiceServer) {
	// If the following call pancis, it indicates UnimplementedCacheRebuilderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheRebuilderService_ServiceDesc, srv)
}

func _CacheRebuilderService_TriggerRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheRebuilderServiceServer).TriggerRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheRebuilderService_TriggerRebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheRebuilderServiceServer).TriggerRebuild(ctx, req.(*TriggerRebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheRebuilderService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheRebuilderServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheRebuilderService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheRebuilderServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheRebuilderService_ServiceDesc is the grpc.ServiceDesc for CacheRebuilderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheRebuilderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache_rebuilder.CacheRebuilderService",
	HandlerType: (*CacheRebuilderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerRebuild",
			Handler:    _CacheRebuilderService_TriggerRebuild_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _CacheRebuilderService_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache_rebuilder/cache_rebuilder.proto",
}
