// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: likes/likes.proto

package likespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LikesService_CreateLike_FullMethodName = "/likes.LikesService/CreateLike"
	LikesService_HasLiked_FullMethodName   = "/likes.LikesService/HasLiked"
	LikesService_Unlike_FullMethodName     = "/likes.LikesService/Unlike"
	LikesService_Reset_FullMethodName      = "/likes.LikesService/Reset"
)

// LikesServiceClient is the client API for LikesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikesServiceClient interface {
	CreateLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*CreateLikeResponse, error)
	HasLiked(ctx context.Context, in *HasLikedRequest, opts ...grpc.CallOption) (*HasLikedResponse, error)
	Unlike(ctx context.Context, in *UnlikeRequest, opts ...grpc.CallOption) (*UnlikeResponse, error)
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
}

type likesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLikesServiceClient(cc grpc.ClientConnInterface) LikesServiceClient {
	return &likesServiceClient{cc}
}

func (c *likesServiceClient) CreateLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*CreateLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLikeResponse)
	err := c.cc.Invoke(ctx, LikesService_CreateLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likesServiceClient) HasLiked(ctx context.Context, in *HasLikedRequest, opts ...grpc.CallOption) (*HasLikedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasLikedResponse)
	err := c.cc.Invoke(ctx, LikesService_HasLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likesServiceClient) Unlike(ctx context.Context, in *UnlikeRequest, opts ...grpc.CallOption) (*UnlikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeResponse)
	err := c.cc.Invoke(ctx, LikesService_Unlike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likesServiceClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, LikesService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikesServiceServer is the server API for LikesService service.
// All implementations must embed UnimplementedLikesServiceServer
// for forward compatibility.
type LikesServiceServer interface {
	CreateLike(context.Context, *CreateLikeRequest) (*CreateLikeResponse, error)
	HasLiked(context.Context, *HasLikedRequest) (*HasLikedResponse, error)
	Unlike(context.Context, *UnlikeRequest) (*UnlikeResponse, error)
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	mustEmbedUnimplementedLikesServiceServer()
}

// UnimplementedLikesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLikesServiceServer struct{}

func (UnimplementedLikesServiceServer) CreateLike(context.Context, *CreateLikeRequest) (*CreateLikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLike not implemented")
}
func (UnimplementedLikesServiceServer) HasLiked(context.Context, *HasLikedRequest) (*HasLikedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasLiked not implemented")
}
func (UnimplementedLikesServiceServer) Unlike(context.Context, *UnlikeRequest) (*UnlikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlike not implemented")
}
func (UnimplementedLikesServiceServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedLikesServiceServer) mustEmbedUnimplementedLikesServiceServer() {}
func (UnimplementedLikesServiceServer) testEmbeddedByValue()                      {}

// UnsafeLikesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikesServiceServer will
// result in compilation errors.
type UnsafeLikesServiceServer interface {
	mustEmbedUnimplementedLikesServiceServer()
}

func RegisterLikesServiceServer(s grpc.ServiceRegistrar, srv LikesServiceServer) {
	// If the following call pancis, it indicates UnimplementedLikesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LikesService_ServiceDesc, srv)
}

func _LikesService_CreateLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServiceServer).CreateLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikesService_CreateLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServiceServer).CreateLike(ctx, req.(*CreateLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikesService_HasLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServiceServer).HasLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikesService_HasLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServiceServer).HasLiked(ctx, req.(*HasLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikesService_Unlike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServiceServer).Unlike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikesService_Unlike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServiceServer).Unlike(ctx, req.(*UnlikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikesService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikesService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServiceServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LikesService_ServiceDesc is the grpc.ServiceDesc for LikesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LikesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "likes.LikesService",
	HandlerType: (*LikesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLike",
			Handler:    _LikesService_CreateLike_Handler,
		},
		{
			MethodName: "HasLiked",
			Handler:    _LikesService_HasLiked_Handler,
		},
		{
			MethodName: "Unlike",
			Handler:    _LikesService_Unlike_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _LikesService_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "likes/likes.proto",
}
