// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: likes/likes.proto

package likespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_likes_likes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{0}
}

func (x *Like) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Like) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Like) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type CreateLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLikeRequest) Reset() {
	*x = CreateLikeRequest{}
	mi := &file_likes_likes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeRequest) ProtoMessage() {}

func (x *CreateLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeRequest.ProtoReflect.Descriptor instead.
func (*CreateLikeRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLikeRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type CreateLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Like          *Like                  `protobuf:"bytes,1,opt,name=like,proto3" json:"like,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLikeResponse) Reset() {
	*x = CreateLikeResponse{}
	mi := &file_likes_likes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLikeResponse) ProtoMessage() {}

func (x *CreateLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLikeResponse.ProtoReflect.Descriptor instead.
func (*CreateLikeResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLikeResponse) GetLike() *Like {
	if x != nil {
		return x.Like
	}
	return nil
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_likes_likes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{3}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_likes_likes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_likes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_likes_likes_proto_rawDescGZIP(), []int{4}
}

func (x *ResetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_likes_likes_proto protoreflect.FileDescriptor

const file_likes_likes_proto_rawDesc = "" +
	"\n" +
	"\x11likes/likes.proto\x12\x05likes\"L\n" +
	"\x04Like\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\"I\n" +
	"\x11CreateLikeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\"5\n" +
	"\x12CreateLikeResponse\x12\x1f\n" +
	"\x04like\x18\x01 \x01(\v2\v.likes.LikeR\x04like\"\x0e\n" +
	"\fResetRequest\"'\n" +
	"\rResetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x85\x01\n" +
	"\fLikesService\x12A\n" +
	"\n" +
	"CreateLike\x12\x18.likes.CreateLikeRequest\x1a\x19.likes.CreateLikeResponse\x122\n" +
	"\x05Reset\x12\x13.likes.ResetRequest\x1a\x14.likes.ResetResponseBMZKgithub.com/vahan-sahakyan/distributed-social-network/pkg/grpc/likes;likespbb\x06proto3"

var (
	file_likes_likes_proto_rawDescOnce sync.Once
	file_likes_likes_proto_rawDescData []byte
)

func file_likes_likes_proto_rawDescGZIP() []byte {
	file_likes_likes_proto_rawDescOnce.Do(func() {
		file_likes_likes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_likes_likes_proto_rawDesc), len(file_likes_likes_proto_rawDesc)))
	})
	return file_likes_likes_proto_rawDescData
}

var file_likes_likes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_likes_likes_proto_goTypes = []any{
	(*Like)(nil),               // 0: likes.Like
	(*CreateLikeRequest)(nil),  // 1: likes.CreateLikeRequest
	(*CreateLikeResponse)(nil), // 2: likes.CreateLikeResponse
	(*ResetRequest)(nil),       // 3: likes.ResetRequest
	(*ResetResponse)(nil),      // 4: likes.ResetResponse
}
var file_likes_likes_proto_depIdxs = []int32{
	0, // 0: likes.CreateLikeResponse.like:type_name -> likes.Like
	1, // 1: likes.LikesService.CreateLike:input_type -> likes.CreateLikeRequest
	3, // 2: likes.LikesService.Reset:input_type -> likes.ResetRequest
	2, // 3: likes.LikesService.CreateLike:output_type -> likes.CreateLikeResponse
	4, // 4: likes.LikesService.Reset:output_type -> likes.ResetResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_likes_likes_proto_init() }
func file_likes_likes_proto_init() {
	if File_likes_likes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_likes_likes_proto_rawDesc), len(file_likes_likes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_likes_likes_proto_goTypes,
		DependencyIndexes: file_likes_likes_proto_depIdxs,
		MessageInfos:      file_likes_likes_proto_msgTypes,
	}.Build()
	File_likes_likes_proto = out.File
	file_likes_likes_proto_goTypes = nil
	file_likes_likes_proto_depIdxs = nil
}
