{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
spec:
  selector:
    app: {{ $name }}-service
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
    {{- if $svc.grpcPort }}
    - name: grpc
      port: {{ $svc.grpcPort }}
      targetPort: {{ $svc.grpcPort }}
    {{- end }}
  type: ClusterIP
{{- end }}
