#!/usr/bin/env bash
# Writes each service Dockerfile, copying only the pkg/ dirs the service imports.
# Usage: ./scripts/gen-dockerfiles.sh
#        or via: make dockerfiles
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODULE_PREFIX="github.com/vahan-sahakyan/distributed-social-network/pkg/"

for svc_dir in "$REPO_ROOT"/services/*/; do
  svc=$(basename "$svc_dir")
  dockerfile="$svc_dir/Dockerfile"

  if [[ ! -f "$dockerfile" ]]; then
    continue
  fi

  # collect pkg/* import paths used by this service, sorted
  pkg_deps=$(
    cd "$svc_dir" && go list -deps ./... 2>/dev/null \
      | grep "^${MODULE_PREFIX}" \
      | sed "s|${MODULE_PREFIX}|pkg/|" \
      | sort -u
  )

  if [[ -z "$pkg_deps" ]]; then
    echo "  $svc: no pkg/ deps found, skipping"
    continue
  fi

  pkg_copies=""
  while IFS= read -r dep; do
    pkg_copies+="COPY ${dep}/ ./${dep}/"$'\n'
  done <<< "$pkg_deps"

  # go.mod/go.sum first so the download layer survives source changes;
  # cache mounts keep modules and build cache across go.mod changes too
  cat > "$dockerfile" <<EOF
# generated by scripts/gen-dockerfiles.sh
FROM golang:1.27-alpine3.24 AS builder
WORKDIR /app
COPY pkg/go.mod pkg/go.sum ./pkg/
COPY services/${svc}/go.mod services/${svc}/go.sum ./services/${svc}/
WORKDIR /app/services/${svc}
RUN --mount=type=cache,target=/go/pkg/mod go mod download
WORKDIR /app
${pkg_copies}COPY services/${svc}/ ./services/${svc}/
WORKDIR /app/services/${svc}
RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \\
    CGO_ENABLED=0 go build -o /bin/service ./cmd

FROM alpine:3.24
RUN apk --no-cache add ca-certificates
COPY --from=builder /bin/service /service
USER 65532:65532
ENTRYPOINT ["/service"]
EOF

  echo "  updated $svc"
done

echo "done."
