// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: search/search.proto

package searchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostHit struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId  string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Text      string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ImageId   string                 `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Hashtags  []string               `protobuf:"bytes,5,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// text with matches wrapped in <em></em>; empty when only a hashtag matched
	Highlight     string  `protobuf:"bytes,7,opt,name=highlight,proto3" json:"highlight,omitempty"`
	Score         float32 `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostHit) Reset() {
	*x = PostHit{}
	mi := &file_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHit) ProtoMessage() {}

func (x *PostHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHit.ProtoReflect.Descriptor instead.
func (*PostHit) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *PostHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostHit) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *PostHit) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostHit) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *PostHit) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *PostHit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostHit) GetHighlight() string {
	if x != nil {
		return x.Highlight
	}
	return ""
}

func (x *PostHit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UserHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserHit) Reset() {
	*x = UserHit{}
	mi := &file_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHit) ProtoMessage() {}

func (x *UserHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHit.ProtoReflect.Descriptor instead.
func (*UserHit) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *UserHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserHit) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserHit) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserHit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserHit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchPostsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// full text; "#tag" matches the hashtag exactly
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsRequest) Reset() {
	*x = SearchPostsRequest{}
	mi := &file_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsRequest) ProtoMessage() {}

func (x *SearchPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsRequest.ProtoReflect.Descriptor instead.
func (*SearchPostsRequest) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPostsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostHit             `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPostsResponse) Reset() {
	*x = SearchPostsResponse{}
	mi := &file_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPostsResponse) ProtoMessage() {}

func (x *SearchPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPostsResponse.ProtoReflect.Descriptor instead.
func (*SearchPostsResponse) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchPostsResponse) GetPosts() []*PostHit {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *SearchPostsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username prefix or words in the bio
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserHit             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_search_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchUsersResponse) GetUsers() []*UserHit {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TrendingHashtagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         int32                  `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingHashtagsRequest) Reset() {
	*x = TrendingHashtagsRequest{}
	mi := &file_search_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingHashtagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingHashtagsRequest) ProtoMessage() {}

func (x *TrendingHashtagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingHashtagsRequest.ProtoReflect.Descriptor instead.
func (*TrendingHashtagsRequest) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{6}
}

func (x *TrendingHashtagsRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *TrendingHashtagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HashtagCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashtag       string                 `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	Posts         int64                  `protobuf:"varint,2,opt,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashtagCount) Reset() {
	*x = HashtagCount{}
	mi := &file_search_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashtagCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashtagCount) ProtoMessage() {}

func (x *HashtagCount) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashtagCount.ProtoReflect.Descriptor instead.
func (*HashtagCount) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{7}
}

func (x *HashtagCount) GetHashtag() string {
	if x != nil {
		return x.Hashtag
	}
	return ""
}

func (x *HashtagCount) GetPosts() int64 {
	if x != nil {
		return x.Posts
	}
	return 0
}

type TrendingHashtagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashtags      []*HashtagCount        `protobuf:"bytes,1,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingHashtagsResponse) Reset() {
	*x = TrendingHashtagsResponse{}
	mi := &file_search_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingHashtagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingHashtagsResponse) ProtoMessage() {}

func (x *TrendingHashtagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingHashtagsResponse.ProtoReflect.Descriptor instead.
func (*TrendingHashtagsResponse) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{8}
}

func (x *TrendingHashtagsResponse) GetHashtags() []*HashtagCount {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_search_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{9}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_search_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_search_search_proto_rawDescGZIP(), []int{10}
}

func (x *ResetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_search_search_proto protoreflect.FileDescriptor

const file_search_search_proto_rawDesc = "" +
	"\n" +
	"\x13search/search.proto\x12\x06search\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\aPostHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\tR\aimageId\x12\x1a\n" +
	"\bhashtags\x18\x05 \x03(\tR\bhashtags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1c\n" +
	"\thighlight\x18\a \x01(\tR\thighlight\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\"\x98\x01\n" +
	"\aUserHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\"@\n" +
	"\x12SearchPostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"R\n" +
	"\x13SearchPostsResponse\x12%\n" +
	"\x05posts\x18\x01 \x03(\v2\x0f.search.PostHitR\x05posts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"@\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"R\n" +
	"\x13SearchUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.search.UserHitR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"E\n" +
	"\x17TrendingHashtagsRequest\x12\x14\n" +
	"\x05hours\x18\x01 \x01(\x05R\x05hours\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\">\n" +
	"\fHashtagCount\x12\x18\n" +
	"\ahashtag\x18\x01 \x01(\tR\ahashtag\x12\x14\n" +
	"\x05posts\x18\x02 \x01(\x03R\x05posts\"L\n" +
	"\x18TrendingHashtagsResponse\x120\n" +
	"\bhashtags\x18\x01 \x03(\v2\x14.search.HashtagCountR\bhashtags\"\x0e\n" +
	"\fResetRequest\"'\n" +
	"\rResetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xac\x02\n" +
	"\rSearchService\x12F\n" +
	"\vSearchPosts\x12\x1a.search.SearchPostsRequest\x1a\x1b.search.SearchPostsResponse\x12F\n" +
	"\vSearchUsers\x12\x1a.search.SearchUsersRequest\x1a\x1b.search.SearchUsersResponse\x12U\n" +
	"\x10TrendingHashtags\x12\x1f.search.TrendingHashtagsRequest\x1a .search.TrendingHashtagsResponse\x124\n" +
	"\x05Reset\x12\x14.search.ResetRequest\x1a\x15.search.ResetResponseBOZMgithub.com/vahan-sahakyan/distributed-social-network/pkg/grpc/search;searchpbb\x06proto3"

var (
	file_search_search_proto_rawDescOnce sync.Once
	file_search_search_proto_rawDescData []byte
)

func file_search_search_proto_rawDescGZIP() []byte {
	file_search_search_proto_rawDescOnce.Do(func() {
		file_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)))
	})
	return file_search_search_proto_rawDescData
}

var file_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_search_search_proto_goTypes = []any{
	(*PostHit)(nil),                  // 0: search.PostHit
	(*UserHit)(nil),                  // 1: search.UserHit
	(*SearchPostsRequest)(nil),       // 2: search.SearchPostsRequest
	(*SearchPostsResponse)(nil),      // 3: search.SearchPostsResponse
	(*SearchUsersRequest)(nil),       // 4: search.SearchUsersRequest
	(*SearchUsersResponse)(nil),      // 5: search.SearchUsersResponse
	(*TrendingHashtagsRequest)(nil),  // 6: search.TrendingHashtagsRequest
	(*HashtagCount)(nil),             // 7: search.HashtagCount
	(*TrendingHashtagsResponse)(nil), // 8: search.TrendingHashtagsResponse
	(*ResetRequest)(nil),             // 9: search.ResetRequest
	(*ResetResponse)(nil),            // 10: search.ResetResponse
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
}
var file_search_search_proto_depIdxs = []int32{
	11, // 0: search.PostHit.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: search.UserHit.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: search.SearchPostsResponse.posts:type_name -> search.PostHit
	1,  // 3: search.SearchUsersResponse.users:type_name -> search.UserHit
	7,  // 4: search.TrendingHashtagsResponse.hashtags:type_name -> search.HashtagCount
	2,  // 5: search.SearchService.SearchPosts:input_type -> search.SearchPostsRequest
	4,  // 6: search.SearchService.SearchUsers:input_type -> search.SearchUsersRequest
	6,  // 7: search.SearchService.TrendingHashtags:input_type -> search.TrendingHashtagsRequest
	9,  // 8: search.SearchService.Reset:input_type -> search.ResetRequest
	3,  // 9: search.SearchService.SearchPosts:output_type -> search.SearchPostsResponse
	5,  // 10: search.SearchService.SearchUsers:output_type -> search.SearchUsersResponse
	8,  // 11: search.SearchService.TrendingHashtags:output_type -> search.TrendingHashtagsResponse
	10, // 12: search.SearchService.Reset:output_type -> search.ResetResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_search_search_proto_init() }
func file_search_search_proto_init() {
	if File_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_search_proto_rawDesc), len(file_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_search_proto_goTypes,
		DependencyIndexes: file_search_search_proto_depIdxs,
		MessageInfos:      file_search_search_proto_msgTypes,
	}.Build()
	File_search_search_proto = out.File
	file_search_search_proto_goTypes = nil
	file_search_search_proto_depIdxs = nil
}
