// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: feed/feed.proto

package feedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	LikesCount    int32                  `protobuf:"varint,4,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentsCount int32                  `protobuf:"varint,5,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *FeedItem) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *FeedItem) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *FeedItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FeedItem) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *FeedItem) GetCommentsCount() int32 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *FeedItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *FeedItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetHomeFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeFeedRequest) Reset() {
	*x = GetHomeFeedRequest{}
	mi := &file_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeFeedRequest) ProtoMessage() {}

func (x *GetHomeFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeFeedRequest.ProtoReflect.Descriptor instead.
func (*GetHomeFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetHomeFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeedRequest) Reset() {
	*x = GetUserFeedRequest{}
	mi := &file_feed_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeedRequest) ProtoMessage() {}

func (x *GetUserFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeedRequest.ProtoReflect.Descriptor instead.
func (*GetUserFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_feed_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeedResponse) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_feed_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{4}
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_feed_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{5}
}

func (x *ResetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_feed_feed_proto protoreflect.FileDescriptor

const file_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x0ffeed/feed.proto\x12\x04feed\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n" +
	"\bFeedItem\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1f\n" +
	"\vlikes_count\x18\x04 \x01(\x05R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\x05 \x01(\x05R\rcommentsCount\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"-\n" +
	"\x12GetHomeFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x12GetUserFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x0fGetFeedResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\"\x0e\n" +
	"\fResetRequest\"'\n" +
	"\rResetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xbf\x01\n" +
	"\vFeedService\x12>\n" +
	"\vGetHomeFeed\x12\x18.feed.GetHomeFeedRequest\x1a\x15.feed.GetFeedResponse\x12>\n" +
	"\vGetUserFeed\x12\x18.feed.GetUserFeedRequest\x1a\x15.feed.GetFeedResponse\x120\n" +
	"\x05Reset\x12\x12.feed.ResetRequest\x1a\x13.feed.ResetResponseBKZIgithub.com/vahan-sahakyan/distributed-social-network/pkg/grpc/feed;feedpbb\x06proto3"

var (
	file_feed_feed_proto_rawDescOnce sync.Once
	file_feed_feed_proto_rawDescData []byte
)

func file_feed_feed_proto_rawDescGZIP() []byte {
	file_feed_feed_proto_rawDescOnce.Do(func() {
		file_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_feed_proto_rawDesc), len(file_feed_feed_proto_rawDesc)))
	})
	return file_feed_feed_proto_rawDescData
}

var file_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_feed_feed_proto_goTypes = []any{
	(*FeedItem)(nil),              // 0: feed.FeedItem
	(*GetHomeFeedRequest)(nil),    // 1: feed.GetHomeFeedRequest
	(*GetUserFeedRequest)(nil),    // 2: feed.GetUserFeedRequest
	(*GetFeedResponse)(nil),       // 3: feed.GetFeedResponse
	(*ResetRequest)(nil),          // 4: feed.ResetRequest
	(*ResetResponse)(nil),         // 5: feed.ResetResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_feed_feed_proto_depIdxs = []int32{
	6, // 0: feed.FeedItem.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: feed.GetFeedResponse.items:type_name -> feed.FeedItem
	1, // 2: feed.FeedService.GetHomeFeed:input_type -> feed.GetHomeFeedRequest
	2, // 3: feed.FeedService.GetUserFeed:input_type -> feed.GetUserFeedRequest
	4, // 4: feed.FeedService.Reset:input_type -> feed.ResetRequest
	3, // 5: feed.FeedService.GetHomeFeed:output_type -> feed.GetFeedResponse
	3, // 6: feed.FeedService.GetUserFeed:output_type -> feed.GetFeedResponse
	5, // 7: feed.FeedService.Reset:output_type -> feed.ResetResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feed_feed_proto_init() }
func file_feed_feed_proto_init() {
	if File_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_feed_proto_rawDesc), len(file_feed_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_feed_proto_goTypes,
		DependencyIndexes: file_feed_feed_proto_depIdxs,
		MessageInfos:      file_feed_feed_proto_msgTypes,
	}.Build()
	File_feed_feed_proto = out.File
	file_feed_feed_proto_goTypes = nil
	file_feed_feed_proto_depIdxs = nil
}
