{{- if .Values.redpandaConsole.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      securityContext:
        {{- include "dsn.podSecurityContext" .Values.redpandaConsole.security | nindent 8 }}
      containers:
        - name: redpanda-console
          image: {{ .Values.redpandaConsole.image }}
          securityContext:
            {{- include "dsn.securityContext" .Values.redpandaConsole.security | nindent 12 }}
          env:
            - name: KAFKA_BROKERS
              value: redpanda:9092
          resources:
            {{- toYaml .Values.redpandaConsole.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
spec:
  selector:
    app: redpanda-console
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
{{- end }}
