{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
spec:
  selector:
    app: {{ $name }}-service
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
  type: ClusterIP
{{- end }}
